### ISSUE TITLE
Document recommended tidyverse alternatives to purrrlyr functions?

### ISSUE THREAD

**Issue by cboettig** [hadley/purrrlyr#2]
If I understand correctly, these are essentially functions that have been deprecated from tidyverse and have better alternatives?  

> because they have been replaced by other solutions in the tidyverse.

I think it would help folks migrate more easily to the preferred syntax if this package included a quick example of how the same thing is accomplished with tidyverse functions, or at least a quick pointer to the preferred patterns.  

(e.g. I'm still trying to wrap my own head around the best way to iterate an arbitrary function through the rows of a data.frame, a la `dplyr::rowwise`+`dplyr::do`, `purrrlyr::by_rows`, `tidyr::nest` etc.  I'm guessing `nest` is the preferred pattern these days)

**Comment by Deleetdk** [comment]
I still use `plyr::a*ply` (with `.margins = 1`) for these operations. Slower, but the syntax is easy to understand and does not use fancy unquoted expressions/etc so it is easy to write functions with. And has progress bar if needed.
