### ISSUE TITLE
STRING_PTR() can only be applied to a 'character', not a 'list'

### ISSUE THREAD

**Issue by IndrajeetPatil** [hadley/purrrlyr#9]
Changes made to `STRING_PTR()` in `R 3.5.0` has created bugs in `purrrlyr` function `by_row()`-
https://community.rstudio.com/t/string-ptr-can-only-be-applied-to-a-character-not-a-list/18100/9?u=indrajeetpatil

```r
library(tidyverse)
library(purrrlyr)

# dataframe
dat <-
  structure(
    list(
      vars = c("var_1", "var_2"),
      data = list(
        structure(
          list(time = 1:10, value = c(1:10)),
          row.names = c(NA, -10L),
          class = c("tbl_df", "tbl", "data.frame")
        ),
        structure(
          list(time = 1:10, value = c(11:20)),
          row.names = c(NA, -10L),
          class = c("tbl_df", "tbl", "data.frame")
        )
      ),
      mu = c(1, 2),
      stdev = c(1, 2)
    ),
    class = c("tbl_df", "tbl", "data.frame"),
    row.names = c(NA, -2L)
  )

# applying operation row-wise
dat %>%
  purrrlyr::by_row(
    .d = .,
    ..f = ~dnorm(x = .$data[[1]]$value[[1]], mean = .$mu[[1]], sd = .$stdev[[1]]),
    collate = "rows"
  )
#> Error in purrrlyr::by_row(.d = ., ..f = ~dnorm(x = .$data[[1]]$value[[1]], : STRING_PTR() can only be applied to a 'character', not a 'list'
```

**Comment by IndrajeetPatil** [comment]
@lionel-  Is there a planned `CRAN` release of `purrrlyr` sometime soon? 

I am adding some new funtionality in my package that relies on `purrrlyr` which doesn't have the error mentioned here-
> STRING_PTR() can only be applied to a 'character', not a 'list'

Right now I am getting the CI builds to succeed by using `Remotes`, but that won't work with `CRAN`.

**Comment by lionel-** [comment]
It is planned for after the dplyr 0.8.0 release.

**Comment by IndrajeetPatil** [comment]
@lionel- I see that `dplyr 0.8.0` is now on `CRAN`! 
https://cran.r-project.org/web/packages/dplyr/index.html

Will `purrrlyr` be submitted to `CRAN` soon as well?

**Comment by lionel-** [comment]
Just did the revdeps, everything looks good. I'm waiting for win-builder to update to dplyr 0.8.0 so I can check purrrlyr with it.

**Comment by lionel-** [comment]
Now on CRAN!

**Comment by IndrajeetPatil** [comment]
Thank you so much for such a quick response!!
